#!/bin/sh

cat <<EOF
{
  "all": {
    "hosts": [
      "foo",
      "bar"
    ],
    "vars": {
      "ansible_connection": "local",
      ";": "Suppress warning about python path on darwin",
      "ansible_python_interpreter": "/usr/bin/python"
    }
  },
  "group1": {
    "hosts": [
      "foo"
    ]
  },
  "group2": {
    "hosts": [
      "bar"
    ]
  },
  "_meta": {
  }
}
